### ISSUE TITLE
Error messages in the console

### ISSUE THREAD

**Issue by ioanna21** [compas-dev/compas_viewers#11]
**Describe the bug**
Hello, 
I have installed the compas_viewers on Windows using conda, with the latest version of compas and python=3.7.8, 
Although it works, it prints in the console the following error.
Have I installed something wrong, or is this normal? 

Thanks!

```
Traceback (most recent call last):
  File "i:\libraries\compas_viewers\src\compas_viewers\core\glwidget.py", line 86, in initializeGL
    glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB | GLUT_DEPTH)
  File "C:\ProgramData\Anaconda3\envs\compas_slicer\lib\site-packages\OpenGL\platform\baseplatform.py", line 425, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInitDisplayMode, check for bool(glutInitDisplayMode) before calling
Traceback (most recent call last):
  File "i:\libraries\compas_viewers\src\compas_viewers\core\glwidget.py", line 86, in initializeGL
    glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB | GLUT_DEPTH)
  File "C:\ProgramData\Anaconda3\envs\compas_slicer\lib\site-packages\OpenGL\platform\baseplatform.py", line 425, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInitDisplayMode, check for bool(glutInitDisplayMode) before calling
Traceback (most recent call last):
  File "i:\libraries\compas_viewers\src\compas_viewers\core\glwidget.py", line 86, in initializeGL
    glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB | GLUT_DEPTH)
  File "C:\ProgramData\Anaconda3\envs\compas_slicer\lib\site-packages\OpenGL\platform\baseplatform.py", line 425, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInitDisplayMode, check for bool(glutInitDisplayMode) before calling
C:\ProgramData\Anaconda3\envs\compas_slicer\lib\site-packages\OpenGL\images.py:142: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  return data.tostring()
```

**Comment by brgcode** [comment]
if this was on windows, please make sure the installation instructions specific for Windows (https://github.com/compas-dev/compas_viewers#windows). for whatever reason OpenGL only works properly on Windows if you use the installer from the page that is listed there...

**Comment by ioanna21** [comment]
I have installed the wheel from that page, but I still get this error.

**Comment by brgcode** [comment]
okay will try to have a look later today then, because that is not supposed to happen...

**Comment by cheibasethz** [comment]
Hi, I have the same error, even after following the instructions specific for Windows (https://github.com/compas-dev/compas_viewers#windows). Can you help me?

**Comment by ioanna21** [comment]
Yesterday during the compas_slicer tutorial, a lot of MAS students also had the same problem. They had installed the PyOpenGL wheel correctly (we verified it), but this error came up. In addition, the usual viewers window didn't appear, instead they had a black vewport with no (visible) geometry, I attach a screenshot. 

![1](https://user-images.githubusercontent.com/17250275/99532364-7472fb80-29a4-11eb-99d5-bd82ca3dcce3.PNG)

**Comment by ioanna21** [comment]
On the other hand for me, once I re-installed everything including the wheel, the error disappeared.

**Comment by brgcode** [comment]
it seems that the new version of `PySide2` is not entirely compatible with the current version of `compas_viewers`. i will try to fix this asap, but i don't have a lot of time right now.

@Licini did you make a frozen install recipe with older versions of the requirements which we know works with the current version of the viewers? can you share this somewhere?
